### ISSUE TITLE
ValueError: Initialize failed for backend: "REFPROP"

### ISSUE THREAD

**Issue by eugenepyvovarov** [usnistgov/REFPROP-issues#39]
### Description

For some project we are using refprop to calculate Compressor model. But after some time the refprop backend jsut stopped working, and we can't find the reason why. We tried all methods from the docs, tried different versions of refprop / python / coolprop etc. Nothing helped.

**Python code we run in docker**

**app.py**

```
from __future__ import division #Make integer 3/2 give 1.5 in python 2.x
import CoolProp.CoolProp as CP

if __name__=='__main__':    
    CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, '/opt/refprop/')
    print(CP.PropsSI('D','P', 101325, 'T', 300, "REFPROP::R22"))
    CP.get_global_param_string("REFPROP_version")
```

**Dockerfile**

```
FROM python:3.6-alpine

# REFPROP requirements
RUN apk --no-cache --update-cache add gcc gfortran build-base wget cmake git bash
RUN pip install numpy six CoolProp 'flask==1.0.2'

# REFPROP
RUN mkdir /opt
COPY 944/ /opt/refprop/
RUN cp -R /opt/refprop/FLUIDS /opt/refprop/fluids
RUN cp -R /opt/refprop/FORTRAN /opt/refprop/fortran
RUN cp -R /opt/refprop/MIXTURES /opt/refprop/mixtures

ADD https://api.github.com/repos/usnistgov/REFPROP-cmake/git/refs/heads/master RPcmake-version.json
RUN cd /root && git clone --recursive https://github.com/usnistgov/REFPROP-cmake.git
RUN mkdir /root/REFPROP-cmake/build
WORKDIR /root/REFPROP-cmake/build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release -DREFPROP_FORTRAN_PATH=/opt/refprop/fortran
RUN cmake --build .
RUN cp librefprop.so /usr/local/lib/librefprop.so
RUN cp librefprop.so /usr/local/include/librefprop.so

# app
COPY . /usr/src/app/
WORKDIR /usr/src/app/

CMD ["python", "app.py"]
```

### Steps to Reproduce

1. docker build -t refprop .
2. docker run refprop

**Expected behavior:** 
expect to see 
_996.5569352646376_

**Actual behavior:** 

```
Traceback (most recent call last):
  File "Compressor_initial.py", line 6, in <module>
    print(CP.PropsSI('D','P', 101325, 'T', 300, "REFPROP::R22"))
  File "CoolProp/CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:36859)
  File "CoolProp/CoolProp.pyx", line 408, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:36644)
  File "CoolProp/CoolProp.pyx", line 297, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:34849)
ValueError: Initialize failed for backend: "REFPROP", fluid: "R22" fractions "[ 1.0000000000 ]"; error: Could not load these fluids: R22 : PropsSI("D","P",101325,"T",300,"REFPROP::R22")
```

### Versions

**REFPROP Version:** 9.4.4.44 (004)
**Operating System and Version:**  Alpine Linux 3.8
**Access Method:** Python

**Comment by ianhbell** [comment]
I bet I know what is going on - the 9.4.4 beta expires, but I bet you don’t have any way of seeing that error message.  Upgrade to 10.0 and you should be in business.  Or downgrade to 9.1.1.  Weird - CoolProp should have passed along that message.

**Comment by ianhbell** [comment]
Did that fix it?

**Comment by eugenepyvovarov** [comment]
We purchased license for refprop 10 but can't download it yet. I've I will
have the source I will check and update you. Thanks!

пт, 17 авг. 2018 г., 12:12 AM Ian Bell <notifications@github.com>:

**Comment by eugenepyvovarov** [comment]
With v10 everything works fine, thanks a lot!

**Comment by ianhbell** [comment]
Excellent, thanks for the update!
